### ISSUE TITLE
Nuevo proyecto: mejorar Manejo de errores

### ISSUE THREAD

**Issue by fdodino** [juanpablocamejo/shutterlync#1]
Está mostrando correctamente los campos en rojo pero falta incorporar un mensaje de error para cada uno.

Cuando ingresás un cliente cuyo mail ya está registrado, el feedback del backend no llega a mostrarse en el frontend.

**Comment by juanpablocamejo** [comment]
Resuelto en el siguiente commit: 
https://github.com/juanpablocamejo/ShutterLync-frontend/commit/8fd8e3893ff0f2133a7d94bebaa9ab987e8fa5b5
